# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  displayName: create a nginx deployment with kubectl commands
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-ash'
    namespace: 'nginx'
    command: 'create'
    arguments: 'deployment nginx --image=nginx:latest'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
